## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1a Read the WeatherPy_vacation.csv into a DataFrame.
# Store the CSV you saved created in part one into a DataFrame.
vacation_df = pd.read_csv("WeatherPy_vacation(final).csv")
vacation_df.head(10)

City_ID           City Country  Max Temp    Lat     Lng  \
0        0           Ruwi      OM     68.00  23.60   58.55   
1        5      Mahebourg      MU     73.40 -20.41   57.70   
2        6          Buala      SB     84.29  -8.14  159.59   
3       12      Oriximina      BR     80.67  -1.77  -55.87   
4       18         Dingle      PH     77.88  11.00  122.67   
5       19         Hasaki      JP     68.00  35.73  140.83   
6       21        Itarema      BR     79.79  -2.92  -39.92   
7       22  San Cristobal      VE     78.80   7.77  -72.22   
8       23        Rikitea      PF     73.72 -23.12 -134.97   
9       24          Arlit      NE     75.31  18.74    7.39   

                           Hotel Name  
0                      Al Falaj Hotel  
1  Shandrani Beachcomber Resort & Spa  
2                Maringe Lagoon Lodge  
3                  Pousada Tia Amélia  
4                         Camp Pasica  
5               Inubosaki Kanko Hotel  
6                         Windvillage  
7                            Pirineos  
8                      Pension Maro'i  
9                Hôtel Telwa Bungalow

In [3]:
# 1b Store the CSV you saved created in part one into a DataFrame.
clean_hotel_df = pd.read_csv("WeatherPy_Database.csv")
clean_hotel_df.head(10)

City_ID             City Country    Lat     Lng  Max Temp  Humidity  \
0        0          Fortuna      US  40.60 -124.16     66.99        77   
1        1          Cordoba      AR -31.41  -64.18     77.00        20   
2        2        Mahebourg      MU -20.41   57.70     71.60        73   
3        3  Arraial Do Cabo      BR -22.97  -42.03     70.45        73   
4        4           Kodiak      US  57.79 -152.41     28.40        42   
5        5    San Policarpo      PH  12.18  125.51     79.74        83   
6        6         Hermanus      ZA -34.42   19.23     64.00        90   
7        7            Vaini      TO -21.20 -175.20     80.60        78   
8        8     Nova Olimpia      BR -14.80  -57.29     84.06        45   
9        9       Nanortalik      GL  60.14  -45.24     39.16        84   

   Cloudiness  Wind Speed  
0           1        3.31  
1           0       13.87  
2          75        2.24  
3          90       17.43  
4           1       21.92  
5         100        6.26  
6          77       12.71  
7          20       13.87  
8          42        1.88  
9         100       17.58

In [21]:
clean_hotel_df = vacation_df
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [22]:
# 4a. Add a marker layer for each city to the map.
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [23]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start_df = vacation_df.loc[vacation_df["City"] == "Laguna"]
vacation_end_df = vacation_df.loc[vacation_df["City"] == "Laguna"]
vacation_stop1_df = vacation_df.loc[vacation_df["City"] == "Kapaa"]
vacation_stop2_df = vacation_df.loc[vacation_df["City"] == "Waipawa"] 
vacation_stop3_df = vacation_df.loc[vacation_df["City"] == "Innisfail"] 

In [26]:
# df = pd.DataFrame({"A": [1, 2], "B": [3.0, 4.5]})
# df.to_numpy()
# array([[1. , 3. ],
#        [2. , 4.5]])

import numpy as np

# start = vacation_start[{"Lat","Lng"}].to_numpy()
# start

In [28]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start_df.to_numpy()
start

array([[154, 'Laguna', 'US', 68.0, 38.42, -121.42,
        'Holiday Inn Express & Suites Elk Grove Central - Hwy 99']],
      dtype=object)

In [9]:
end = vacation_end_df.to_numpy()
end

array([[154, 'Laguna', 'US', 68.0, 38.42, -121.42,
        'Holiday Inn Express & Suites Elk Grove Central - Hwy 99']],
      dtype=object)

In [10]:
stop1 = vacation_stop1_df.to_numpy()
stop1

array([[52, 'Kapaa', 'US', 82.4, 22.08, -159.32,
        'Sheraton Kauai Resort at Coconut Beach']], dtype=object)

In [11]:
stop2 = vacation_stop2_df.to_numpy()
stop2

array([[222, 'Waipawa', 'NZ', 66.2, -41.41, 175.52, 'Tora Coastal Walk']],
      dtype=object)

In [12]:
stop3 = vacation_stop3_df.to_numpy()
stop3

array([[143, 'Innisfail', 'AU', 83.3, -17.53, 146.03, 'Moondarra Motel']],
      dtype=object)

In [29]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
# trip = gmaps.directions_layer(start, end, travel_mode="DRIVING")
trip = gmaps.directions_layer(start, end, waypoints=[stop1, stop2, stop3], travel_mode="DRIVING")

fig.add_layer(trip)
fig

TraitError: [[154 'Laguna' 'US' 68.0 38.42 -121.42
  'Holiday Inn Express & Suites Elk Grove Central - Hwy 99']] is not a valid location. Locations must have length 2.

In [ ]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [ ]:
# 11a. Add a marker layer for each city to the map. 
name = itinerary_df["City"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

In [ ]:
# 11a. Add a marker layer for each city to the map. 
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

In [ ]:
# 11a. Add a marker layer for each city to the map. 
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

In [ ]:
# 11a. Add a marker layer for each city to the map. 
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig